### ISSUE TITLE
Example/demo available?

### ISSUE THREAD

**Issue by MadLittleMods** [tkondrashov/thisminute#49]
Is there an example or demo video of this project? I don't want to set this project up just to see it in action

From https://github.com/tkondrashov/thisminute/issues/20, I tried http://thisminute.org/ and http://thisminute.org/sentinel/get_tweet.php but both just timeout

**Comment by tkondrashov** [comment]
Hi @MadLittleMods !
I take my servers down periodically to save myself some money. I'll get them back up in the next day or two and let you know so you can check the application out!

**Comment by tkondrashov** [comment]
@MadLittleMods 
Unfortunately, it looks like Twitter has changed their API policy since the last time I had this running - I've had to reapply to their developer program. However, those links should be back up now, just with some subset of the last tweets I collected instead of live data.
 
On thisminute.org, you can press v to enter a sentiment tagging mode, and hover over each arrow for the sentiment it describes. Your IP has to be whitelisted to actually be able to submit the votes, so the arrows won't do anything. The sentiments are very abstract, but I think they are interesting ways to split up some concepts of language. The tweets you see on the map are just miscellaneous tweets selected for tagging, when the twitter stream is up they update in real-time (just as soon as they get back to me...), and when Pericog is running they are filtered with the model trained on that data. Truth be told, the models never showed revolutionary results with pretrained models or disaster tweet data I found online, and I was never able to tag enough data on my own to try out the sentiments you see, though I'd love to share the theory behind any of the models I've tried over the years.
The get_tweet API is functional: http://thisminute.org/sentinel/get_tweet.php?n=30&format=1 will give you the last 30 tweets in the database in human-readable format (you can mess with the GET parameters). Again, it's just static until I get the API connected again, since no new tweets are entering the database.
The code for this portion of the project is named "sentinel", you can find the version that should be what's on the server in sentinel/html, and the get_tweet API and a couple of others in sentinel/html/sentinel.
The code for the portion of the project that's responsible for pulling tweets from Twitter is called "archivist", and the meat of it is just an external library. There is some custom code in archivist.php and lib/Consumer.php but it's just some formatting and the DB insert calls.

"Pericog" is the ML portion of the project, which at one pointed filtered the tweets that are displayed on the map page, but currently sentinel is in this data tagging mode where it just displays some miscellaneous selection of tweets. The results when it was running were interesting, but not cutting-edge or anything I'd put on a production site. I'd love to get enough data to train it again and improve the accuracy, but alas tagging data is hard, and I'd really like to try my sentiments as a next step and leap in NLP theory rather than settling for a commercial sentiment analysis tool.

**Comment by MadLittleMods** [comment]
Thanks @tkondrashov. It'd be nice to have these on the readme to have some better context

For future onlookers,

![](https://i.imgur.com/NvYhu9K.png)

v to enter a sentiment tagging mode,

![](https://i.imgur.com/lkkdHld.png)
